# 이 워크플로우의 이름을 지정합니다.
name: Build and Push to ECR

# 'main' 브랜치에 푸시 이벤트가 발생했을 때 이 워크플로우를 실행합니다.
on:
  push:
    branches: [main]
  workflow_dispatch: # 수동 실행을 위해 추가

# 워크플로우는 'build-and-push'라는 하나의 잡(job)으로 구성됩니다.
jobs:
  build-and-push:
    permissions:
      contents: read
      # packages: write
    # 이 잡을 실행할 가상 머신의 종류를 지정합니다.
    runs-on: ubuntu-latest

    # 이 잡에서 실행될 단계(step)들을 정의합니다.
    steps:
      # 1. 소스 코드를 체크아웃합니다.
      - name: Checkout repository
        uses: actions/checkout@v6

      # AWS Credentials -> 적절한 정책(권한)을 가진 사용자
      # IAM? User? (S3, Bedrock 등을 할 때...)

      - name: AWS crendentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # vars로 하셔도 됩니다
      
      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG